"""Freeze the catalog: render the HSS subset CSV as an importable module.

Deterministic codegen — re-running on unchanged data is idempotent, so the
catalog can be hashed and stamped into calibration artifacts.

Usage:
    uv run python -m scripts.data.generate_catalog
"""

from pathlib import Path

from scripts.data.hss_filter import load_hss, read_header_line

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
INPUT_PATH = REPO_ROOT / "data" / "HSS_subset.csv"
OUTPUT_PATH = REPO_ROOT / "src" / "trussRL" / "catalog_data.py"

COST_PER_LB_USD = 1.60
DROP_COLUMNS = ("Type", "EDI_Std_Nomenclature", "AISC_Manual_Label", "T_F")
REQUIRED_PROPERTIES = ("W", "A", "rx", "ry")

GENERATED_HEADER = (
    '"""GENERATED by scripts.data.generate_catalog from data/HSS_subset.csv '
    "— DO NOT EDIT.\n"
    "\n"
    "Regenerate with: uv run python -m scripts.data.generate_catalog\n"
    '"""'
)


def property_columns(header_fields: list[str]) -> dict[str, int]:
    """Map each property name to its imperial (first-occurrence) column index.

    Assumptions:
        1. The CSV header repeats every column name for the metric block, so
           only the first occurrence of each name — the imperial value — is
           kept; the unnamed blank column and identity/flag columns
           (``Type``, nomenclature labels, ``T_F``) are dropped.

    Args:
        header_fields: raw header line split on commas, in file order

    Returns:
        dict: property name mapped to the column index of its value in the file order
    """
    columns: dict[str, int] = {}
    for index, name in enumerate(header_fields):
        if name and name not in DROP_COLUMNS and name not in columns:
            columns[name] = index
    return columns


def parse_row(row: tuple[str, ...], columns: dict[str, int]) -> dict[str, float]:
    """Extract the float-valued properties of one catalog row.

    Assumptions:
        1. Fields that do not parse as a float are silently dropped, so each
           shape carries only the properties the AISC database defines for it.
        2. Appends the derived ``cost_per_ft_usd`` = W x COST_PER_LB_USD as the last key

    Args:
        row: one CSV data row as raw field strings, in file order
        columns: property name mapped to imperial column index

    Returns:
        dict: property name mapped to its float value, in column order,
            with ``cost_per_ft_usd`` appended

    Raises:
        ValueError: if any of the required properties (W, A, rx, ry) is
            missing or non-numeric.
    """
    properties: dict[str, float] = {}
    for name, index in columns.items():
        try:
            properties[name] = float(row[index])
        except ValueError:
            continue
    missing = [name for name in REQUIRED_PROPERTIES if name not in properties]
    if missing:
        raise ValueError(f"row is missing required properties {missing}")
    properties["cost_per_ft_usd"] = properties["W"] * COST_PER_LB_USD
    return properties


def build_catalog(
    header_fields: list[str], rows: list[tuple[str, ...]]
) -> dict[str, dict[str, float]]:
    """Build the designation properties dict for every catalog row.

    Assumptions:
        1. Keys are canonical AISC manual labels, stripped and uppercased,
           kept in CSV row order so rendering is deterministic.

    Args:
        header_fields: raw header line split on commas, in file order
        rows: all CSV data rows as raw field strings

    Returns:
        dict: canonical designation mapped to its property dict

    Raises:
        ValueError: if two rows share a canonical designation, or a row is
            missing a required property.
    """
    columns = property_columns(header_fields)
    label_index = header_fields.index("AISC_Manual_Label")
    catalog: dict[str, dict[str, float]] = {}
    for row in rows:
        designation = row[label_index].strip().upper()
        if designation in catalog:
            raise ValueError(f"duplicate designation {designation!r}")
        try:
            catalog[designation] = parse_row(row, columns)
        except ValueError as error:
            raise ValueError(f"{designation!r}: {error}") from error
    return catalog


def render_module(catalog: dict[str, dict[str, float]]) -> str:
    """Render the catalog dict as deterministic Python source.

    Assumptions:
        1. Floats are rendered with ``repr`` and one key per line, so
           regenerating from an unchanged CSV produces byte-identical
           output (empty ``git diff``).

    Args:
        catalog: canonical designation mapped to its property dict

    Returns:
        str: complete source text of the generated module
    """
    lines = [
        GENERATED_HEADER,
        "",
        f"COST_PER_LB_USD: float = {COST_PER_LB_USD!r}",
        "",
        "CATALOG_DATA: dict[str, dict[str, float]] = {",
    ]
    for designation, properties in catalog.items():
        lines.append(f'    "{designation}": {{')
        for name, value in properties.items():
            lines.append(f'        "{name}": {value!r},')
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> None:
    """Generate ``src/trussRL/catalog_data.py`` from ``data/HSS_subset.csv``.

    Args: None

    Returns: None
    """
    header_fields = read_header_line(INPUT_PATH).split(",")
    df = load_hss(INPUT_PATH)
    rows = [tuple(row) for row in df.itertuples(index=False, name=None)]
    catalog = build_catalog(header_fields, rows)
    OUTPUT_PATH.write_text(render_module(catalog), encoding="utf-8")
    print(f"wrote {len(catalog)} sections -> {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
